export const groups = {
	zako: {
		short: "zako派",
		name: "zako派",
		color: "#87CEEB",
		image: "ext:群友杀/image/groups/zako.png",
	},
	waijing: {
		short: "歪经派",
		name: "歪经派",
		color: "#32CD32",
		image: "ext:群友杀/image/groups/waijing.png",
	},
	feisheng: {
		short: "飞升派",
		name: "飞升派",
		color: "#BA55D3",
		image: "ext:群友杀/image/groups/feisheng.png",
	},
	shigan: {
		short: "实干派",
		name: "实干派",
		color: "#FF4500",
		image: "ext:群友杀/image/groups/shigan.png",
	},
	aoye: {
		short: "熬夜派",
		name: "熬夜派",
		color: "#2F4F4F",
		image: "ext:群友杀/image/groups/aoye.png",
	}
};

export const intro = {
	testcharacter: "一个测试用角色",
	KK_jiang: "一只可爱的KK猫哦~",
	lianyu: "可以摸摸尾巴的小教主",
	huli: "护食的狐仙狐黎",
	Censored: "哦我的天哪，这[Censored]的可太[Censored]了，这[Censored]绝对是我见过最[Censored]的东西！不！知！所！措！",
	yunjian: "慕璃的笨猫猫",
	Hina: "空崎日奈（不正经）",
	ailisi: "爱打游戏的爱丽丝酱~",
	kaiyi: "吾之存在，为践行王女意志而生",
	chengzi: "为什么是橙子，因为诚子爱吃橙子，三角洲大肘子！",
	shijiu: "乌鲁鲁人柱力！",
	aili: "不正经的粉毛爱莉",
	lvren: "背上了行囊~行之无悔的旅人",
	zhizimeng: "man~肘击王牢梦是也",
	dajiejie: "“扣死你~”歪经的大姐姐如是说",
	manbu: "漫步~漫步·~哈基米漫步~（哔---）",
	yuchuanluo: "羽川川川川川川川洛<br>Raaaaaaaaaaku！！！",
	kongmeng: "你这只弱受杂鱼猫娘！",
	xiaoxiao: "群里的经典夜猫子的说",
	sb_dajiejie: "大姐姐plus pro max！海量的体力，你扣不动的存在！（乖乖挨扣吧）",
	zuolaobai: "叫我大牢白",
	jinbihai: "一枚爱潜水的虾米",
	sb_zuolaobai: "就是看不惯坐牢怎么了？咱牢白坐牢了大半辈子还不能享受享受吗（bushi）",
	yuqiu: "一吃爱吃杂鱼の猫猫",
	sb_yunjian: "闲云一片挂窗边，偶落风前作信笺。<br>写到斜阳沉未竟，空余墨色染茶烟。",
	shen_lvren: "明明厌恶着孤独，却从未离开过深渊的边缘",
	re_KK_jiang: "杂鱼kk的救赎之路",
	lifu_Hina: "穿上了礼服的日奈，将会带给我们令人期待的演出",
	luoming: "神奇的穷神吗？有点意思！",
	shen_mojiexianjun_zuolaobai: "吾代天子掌朝，谁敢不尊谁敢不从！",
};

export const character = {
	testcharacter: {
		sex: "double",
		group: "shigan",
		hp: 5,
		maxHp: 10,
		hujia: 5,
		isAiForbidden: true,
		skills: ["test1", "test2"],
	},
	KK_jiang: {
		sex: "male",
		group: "zako",
		hp: 4,
		dualSideCharacter: "testcharacter",
		skills: ["keai", "zako_dejiban", "haqi", "wodaoyaokankan"],
	},
	lianyu: {
		sex: "male",
		group: "waijing",
		hp: 3,
		skills: ["mengwu", "nihenbangle", "jiayou"],
	},
	huli: {
		sex: "male",
		group: "waijing",
		hp: 5,
		skills: ["hufeng", "dengxian", "nizhendehenbang", "heshu"],
	},
	Censored: {
		sex: "none",
		group: "feisheng",
		hp: 4,
		skills: ["Restrict", "Permissions", "Root", "Database"],
	},
	yunjian: {
		sex: "male",
		group: "shigan",
		hp: 3,
		isZhugong: true,
		skills: ["lingguang", "gousi", "gongmian"],
	},
	Hina: {
		sex: "female",
		group: "aoye",
		hp: 3,
		skills: ["zhongmu", "fancha", "guangzhiyongzhe_lianjie"],
	},
	ailisi: {
		sex: "female",
		group: "aoye",
		hp: 4,
		dualSideCharacter: "kaiyi",
		skills: ["dualside", "zuduishenqing", "guangzhijian_shouhu", "wumingwangnv", "yongzhedezeren"],
	},
	kaiyi: {
		sex: "female",
		group: "aoye",
		hp: 4,
		maxHp: 7,
		isUnseen: true,
		dualSideCharacter: "ailisi",
		skills: ["dualside", "jianglin", "guangzhijian_chongneng", "guangzhijian_zuidaedinggonglv", "guangzhijian_huimie", "huimiedeyaoshi", "wangnvdeyiyuan"]
	},
	chengzi: {
		sex: "male",
		group: "feisheng",
		hp: 9,
		skills: ["feitiandazhou", "lurenwangdefanying", "chudifantan", "jiuchengsanwujin"],
	},
	shijiu: {
		sex: "male",
		group: "feisheng",
		hp: 4,
		skills: ["xunhangdaodan", "niaoshoushourenzhuli", "jiuzhuandacheng"],
	},
	aili: {
		sex: "female",
		group: "waijing",
		hp: 6,
		skills: ["aidechuanbo", "aishen", "fenseyaojing"],
	},
	lvren: {
		sex: "male",
		group: "feisheng",
		hp: 4,
		skills: ["yuanxing", "xurui", "wuhui"],
	},
	zhizimeng: {
		sex: "double",
		group: "feisheng",
		hp: 6,
		maxHp: 12,
		skills: ["huigui", "huizhang", "danchun", "huanzhai"],
	},
	dajiejie: {
		sex: "female",
		group: "waijing",
		hp: 2,
		isZhugong: true,
		skills: ["koukoukongjian", "wobinida", "woyizhidouzai", "chuangzaozhelianjie"],
	},
	manbu: {
		sex: "male",
		group: "zako",
		hp: 4,
		isZhugong: true,
		skills: ["huahaimanbu", "manbomanbo", "manyou", "zako_dejiban"],
	},
	yuchuanluo: {
		sex: "double",
		group: "waijing",
		hp: 4,
		maxHp: 5,
		isZhugong: true,
		skills: ["shujugongxiang", "bug", "lianxieguankong", "qishizhengjing"],
	},
	kongmeng: {
		sex: "female",
		group: "zako",
		hp: 12,
		isZhugong: true,
		skills: ["zako_zhiwang", "caibushizayumaoniang", "zayu", "zako_dejiban"],
	},
	xiaoxiao: {
		sex: "male",
		group: "aoye",
		hp: 4,
		isZhugong: true,
		skills: ["daka", "yeyou", "yexing"],
	},
	sb_dajiejie: {
		sex: "female",
		group: "waijing",
		hp: 100,
		skills: ["yuanzexingwenti", "wojiushiyuanze", "zhanli", "huanji"],
	},
	zuolaobai: {
		sex: "male",
		group: "feisheng",
		hp: 3,
		maxHp: 4,
		skills: ["shiyi", "xiewei", "polao"],
	},
	jinbihai: {
		sex: "male",
		group: "waijing",
		hp: 4,
		maxHp: 5,
		skills: ["xiami", "qianshui", "kapai", "bendan"],
	},
	sb_zuolaobai: {
		sex: "male",
		group: "feisheng",
		hp: 4,
		maxHp: 5,
		skills: ["xueyan", "sb_shiyi", "qiutian", "yili"],
	},
	yuqiu: {
		sex: "female",
		group: "shigan",
		hp: 7,
		skills: ["ranmingbuqudejuejiang", "dumibudingdeduice", "wuweizhongshidekangzheng"],
	},
	sb_yunjian: {
		sex: "male",
		group: "shigan",
		hp: 4,
		isZhugong: true,
		skills: ["qinxue", "sb_gongmian"],
	},
	shen_lvren: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["linyuan", "wangmeng"],
	},
	re_KK_jiang: {
		sex: "male",
		group: "zako",
		hp: 5,
		skills: ["re_haqi", "re_keai", "wodaoyaokankan", "shi_KK_o", "zako_dejiban"],
	},
	lifu_Hina: {
		sex: "female",
		group: "waijing",
		hp: 4,
		skills: ["kaimuyanchu", "zhongmuzhixuanlv", "jiangsinianjituoyuci", "zhoumidezhunbei"],
	},
	luoming: {
		sex: "male",
		group: "feisheng",
		hp: 3,
		skills: ["shenlin", "shijie", "guifashi", "wumianren"],
	},
	shen_mojiexianjun_zuolaobai: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["qys_jiewei", "qys_yizheng", "lishi", "menxin"],
	},
};

export const title = {
	
};
